// "use client";

import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import CopyrightFooter from "./components/CopyrightFooter";
import DataContextProvider from "./context/DataContext";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Cafe de Altura",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <DataContextProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {children}
          <CopyrightFooter />
        </body>
      </html>
    </DataContextProvider>
  );
}
